### PR TITLE
Feature/character reducer

### PR DESCRIPTION
**Pull request by AnaCatanaR**

### CODE REVIEW

**Review by a9nna — APPROVED** [review]
Perfect tests!

**Review by lfilella97 — CHANGES_REQUESTED** [review]
Revisa los code smells

**Review by a9nna — CHANGES_REQUESTED** [review]
Watch out with switch use

**Comment by AnaCatanaR** [comment]
> Revisa los code smells

deleted the unused variable in charactersReducers

**Review by lfilella97 — APPROVED** [review]

**Pull request merged**
